# Docker 이미지 설정 파일
# 이 이미지는 seleniarm/node-chromium:117.0-20230926를 기반으로 만들어집니다.
FROM seleniarm/node-chromium:117.0-20230926

# 환경 변수 설정
ENV LANG=ko_KR.UTF-8
ENV LANGUAGE=ko_KR:ko
ENV TZ=Asia/Seoul

# 컨테이너 실행 시 실행될 명령
CMD ["/opt/bin/entry_point.sh"]
